name: Cachix
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-dev-env:
    name: Generate development environment
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: pkg-pl
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Generate and cache dev environment
        run: |
          nix develop --profile dev-profile --command true
          cachix push pkg-pl dev-profile
