name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  main-release:
    if: github.ref_type == 'branch' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Build Bakage
        run: |
          nix develop --ignore-env --command \
            just build
      - name: Update tag
        run: |
          git push origin :refs/tags/main-release
          git tag -f main-release
          git push origin --tags
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: main-release
          draft: false
          prerelease: true
          files: ./build/bakage.pl
