name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  main-release:
    if: github.ref_type == 'branch' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Update tag
        run: |
          git tag -f main-release
          git push origin --tags
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: main-release
          prerelease: true
          files: bakage.pl
